// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arygadxdevvptxsotfiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyeWdhZHhkZXZ2cHR4c290ZmlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5OTMzNTIsImV4cCI6MjA2NzU2OTM1Mn0.Ji_2QeRcE1VL_UBy2LULDvVPVIjG2QfIBBPtnNB8rCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});